[information]

filename=gsmtw.mrp
appname=…Ò√ÌÃ”Õˆ
appid=30106
version=1001
visible=1
cpu=3
vendor=√∞≈›
description=…Ò√ÌÃ”Õˆ,”ÎªÔ∞ÈPKΩ±“¡À¬£øsohehe4.ysepan.com
include=${MRPBUILDER_HOME}\..\include\, sfw\mrc\, src\, MyWolf\
config=mtk240
#,mtkt240


[config_mtk240]
define=DEMO_DEBUG,CONFIG_240
output=bin\gsmtw.mrp
bmp_mode=normal
#c_compiler=thumb
plat=mtk

[config_game_mtk240]
plugin=app

[config_mtkt240]
define=DEMO_DEBUG,CONFIG_240
output=bin\tghcdjy.mrp
bmp_mode=normal
c_compiler=thumb

[files_mtk240]
file01 = game_mtk240.ext(name=game.ext)
#file02 = ${MRPBUILDER_HOME}\plugins\skyfont\skyfont_mtk.mrp
file03 = ${MRPBUILDER_HOME}\plugins\mainext\mainext_mtk_d.mrp

[files_game_mtk240]
file05 = ${MRPBUILDER_HOME}\plugins\skyfont\skyfont_mtk.lib
file09 = ${MRPBUILDER_HOME}\security\mrpverify_mtk_dbg.lib

file33 = MyWolf\Vi_comm.c
file34 = MyWolf\WI_act3.c
file35 = MyWolf\WI_draw.c
file36 = MyWolf\WI_main.c
file37 = MyWolf\WI_play.c

file38 = main.c
file39 = src\xl_debug.c
file40 = src\xl_bmp.c
file41 = src\fontRead.c
file42 = src\mrc_graphics.c
file43 = src\mrc_android.c
file44 = src\mpc.c
file45 = src\mrc_tool.c
file46 = sfw\mrc\mrc_win.c

[files]

file60=assets\font.mrp
file61=assets\hole.bmp
file63=assets\stone.bmp
file64=assets\player_run_0.bmp
file65=assets\player_run_1.bmp
file66=assets\player_run_2.bmp
file67=assets\player_run_3.bmp
